-- NIGHTRAID Phase 22: Nighty economy administration, audit history, and summaries.
-- Apply after database/phase21.sql. This migration is safe to rerun.

create table if not exists public.nighty_admin_actions (
  id bigint generated by default as identity primary key,
  guild_id text not null,
  admin_id text not null,
  target_id text not null,
  action text not null check (action in ('grant', 'remove', 'set', 'reset_cooldowns')),
  amount bigint not null default 0 check (amount >= 0),
  balance_before bigint not null check (balance_before >= 0),
  balance_after bigint not null check (balance_after >= 0),
  reason text not null check (length(reason) between 1 and 200),
  action_id text not null,
  created_at timestamptz not null default now(),
  unique (guild_id, action_id)
);

create index if not exists nighty_admin_actions_target_idx
  on public.nighty_admin_actions (guild_id, target_id, created_at desc);
create index if not exists nighty_players_balance_idx
  on public.nighty_players (guild_id, balance desc);

create or replace function public.nighty_admin_adjust_balance(
  p_guild_id text,
  p_admin_id text,
  p_target_id text,
  p_operation text,
  p_amount bigint,
  p_reason text,
  p_action_id text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_player public.nighty_players%rowtype;
  v_action public.nighty_admin_actions%rowtype;
  v_before bigint;
  v_after bigint;
begin
  if p_operation not in ('grant', 'remove', 'set')
    or p_amount < 0
    or (p_operation in ('grant', 'remove') and p_amount = 0)
    or length(trim(p_reason)) not between 1 and 200
    or length(p_action_id) < 1 then
    raise exception 'Invalid Nighty admin balance adjustment.';
  end if;

  select * into v_player
  from public.nighty_players
  where guild_id = p_guild_id and user_id = p_target_id
  for update;
  if not found then return jsonb_build_object('status', 'missing_player'); end if;

  select * into v_action from public.nighty_admin_actions
  where guild_id = p_guild_id and action_id = p_action_id;
  if found then
    return to_jsonb(v_action) || jsonb_build_object(
      'status', 'duplicate', 'user_id', v_player.user_id, 'balance', v_player.balance,
      'daily_streak', v_player.daily_streak, 'last_daily_date', v_player.last_daily_date,
      'hunt_available_at', v_player.hunt_available_at, 'battle_available_at', v_player.battle_available_at,
      'total_hunts', v_player.total_hunts, 'total_captures', v_player.total_captures,
      'total_battles', v_player.total_battles, 'total_battle_wins', v_player.total_battle_wins
    );
  end if;

  v_before := v_player.balance;
  v_after := case p_operation
    when 'grant' then v_before + p_amount
    when 'remove' then v_before - p_amount
    else p_amount
  end;
  if v_after < 0 then
    return jsonb_build_object(
      'status', 'insufficient_balance', 'guild_id', p_guild_id,
      'user_id', p_target_id, 'balance', v_player.balance
    );
  end if;

  update public.nighty_players
  set balance = v_after, updated_at = now()
  where guild_id = p_guild_id and user_id = p_target_id
  returning * into v_player;
  insert into public.nighty_admin_actions (
    guild_id, admin_id, target_id, action, amount,
    balance_before, balance_after, reason, action_id
  ) values (
    p_guild_id, p_admin_id, p_target_id, p_operation, p_amount,
    v_before, v_after, trim(p_reason), p_action_id
  ) returning * into v_action;

  insert into public.nighty_ledger (guild_id, user_id, amount, reason, reference_id, balance_after)
  values (
    p_guild_id, p_target_id, v_action.balance_after - v_action.balance_before,
    'admin_' || p_operation, p_action_id, v_action.balance_after
  );
  return to_jsonb(v_action) || jsonb_build_object(
    'status', 'applied', 'user_id', v_player.user_id, 'balance', v_player.balance,
    'daily_streak', v_player.daily_streak, 'last_daily_date', v_player.last_daily_date,
    'hunt_available_at', v_player.hunt_available_at, 'battle_available_at', v_player.battle_available_at,
    'total_hunts', v_player.total_hunts, 'total_captures', v_player.total_captures,
    'total_battles', v_player.total_battles, 'total_battle_wins', v_player.total_battle_wins
  );
end;
$$;

create or replace function public.nighty_admin_reset_cooldowns(
  p_guild_id text,
  p_admin_id text,
  p_target_id text,
  p_reason text,
  p_action_id text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_player public.nighty_players%rowtype;
  v_action public.nighty_admin_actions%rowtype;
begin
  if length(trim(p_reason)) not between 1 and 200 or length(p_action_id) < 1 then
    raise exception 'Invalid Nighty cooldown reset.';
  end if;
  select * into v_player from public.nighty_players
  where guild_id = p_guild_id and user_id = p_target_id
  for update;
  if not found then return jsonb_build_object('status', 'missing_player'); end if;
  select * into v_action from public.nighty_admin_actions
  where guild_id = p_guild_id and action_id = p_action_id;
  if found then
    return to_jsonb(v_action) || jsonb_build_object(
      'status', 'duplicate', 'user_id', v_player.user_id, 'balance', v_player.balance
    );
  end if;

  update public.nighty_players
  set hunt_available_at = null, battle_available_at = null, updated_at = now()
  where guild_id = p_guild_id and user_id = p_target_id
  returning * into v_player;
  delete from public.nighty_game_cooldowns
  where guild_id = p_guild_id and user_id = p_target_id;
  insert into public.nighty_admin_actions (
    guild_id, admin_id, target_id, action, amount,
    balance_before, balance_after, reason, action_id
  ) values (
    p_guild_id, p_admin_id, p_target_id, 'reset_cooldowns', 0,
    v_player.balance, v_player.balance, trim(p_reason), p_action_id
  ) returning * into v_action;
  return to_jsonb(v_action) || jsonb_build_object(
    'status', 'applied', 'user_id', v_player.user_id, 'balance', v_player.balance,
    'daily_streak', v_player.daily_streak, 'last_daily_date', v_player.last_daily_date,
    'hunt_available_at', v_player.hunt_available_at, 'battle_available_at', v_player.battle_available_at,
    'total_hunts', v_player.total_hunts, 'total_captures', v_player.total_captures,
    'total_battles', v_player.total_battles, 'total_battle_wins', v_player.total_battle_wins
  );
end;
$$;

create or replace function public.nighty_economy_summary(p_guild_id text)
returns jsonb
language sql
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'players', (select count(*) from public.nighty_players where guild_id = p_guild_id),
    'total_currency', (select coalesce(sum(balance), 0) from public.nighty_players where guild_id = p_guild_id),
    'average_balance', (select coalesce(floor(avg(balance)), 0) from public.nighty_players where guild_id = p_guild_id),
    'active_listings', (select count(*) from public.nighty_market_listings where guild_id = p_guild_id and status = 'active'),
    'active_challenges', (select count(*) from public.nighty_pvp_challenges where guild_id = p_guild_id and status = 'pending' and expires_at > now()),
    'active_trades', (select count(*) from public.nighty_trade_offers where guild_id = p_guild_id and status = 'pending' and expires_at > now()),
    'active_sessions', (select count(*) from public.nighty_game_sessions where guild_id = p_guild_id and status = 'active' and expires_at > now()),
    'ledger_entries', (select count(*) from public.nighty_ledger where guild_id = p_guild_id)
  );
$$;

alter table public.nighty_admin_actions enable row level security;
revoke all on table public.nighty_admin_actions from anon, authenticated;
grant all on table public.nighty_admin_actions to service_role;
revoke all on function public.nighty_admin_adjust_balance(text, text, text, text, bigint, text, text) from public, anon, authenticated;
revoke all on function public.nighty_admin_reset_cooldowns(text, text, text, text, text) from public, anon, authenticated;
revoke all on function public.nighty_economy_summary(text) from public, anon, authenticated;
grant execute on function public.nighty_admin_adjust_balance(text, text, text, text, bigint, text, text) to service_role;
grant execute on function public.nighty_admin_reset_cooldowns(text, text, text, text, text) to service_role;
grant execute on function public.nighty_economy_summary(text) to service_role;

comment on table public.nighty_admin_actions is 'Protected audit history for every Nighty economy administration action.';
